apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  type: LoadBalancer
  selector:
    app: redmine
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002